### ISSUE TITLE
0.14.0 Plan

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-maven#213]
### Legend of annotations

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

### Plan Items
- [x] Investigate that`mvn -Pprofile` doesn't take effect #117 #175 [A user review](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven#review-details)
  (**Note**: Not able to reproduce. )
- [x] Fix WSL path conversion #206  
  Fixed in #217 
- [ ] 🔵 Investigate that VSCode crashes on 4G-RAM MacOSX. #172 
- [x] Remove outdated BI events. 
  Completed by PR #218 
- [x] Completion for groupId/artifactId leveraging info from Maven Central Repository #195 
  Done by PR #221 #222 #223 
- [x] Fix the issue that mvn help:describe keeps grabbing the focus in MacOSX #214 
  Fixed in PR #219
