### ISSUE TITLE
v0.10.0 Plan

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-maven#76]
- [x] Hide Maven view by default #51 ( completed in PR #80 )
- [ ] ~~~Improve user experience for editing pom.xml #47~~~ (Moved to next version)
- [x] Create separate terminals for each root folder #68 ( completed with PR #83 )
- [x] Force to use mvnw if found. #84 ( PR #88 ) add a config to turn on/off
- [x] Refactor maven projects explorer ( completed with PR #83 )
- [x] Improve performance of searching for pom.xml #77 ( completed with PR #83 )
- [x] Includes archetypes in local catalog when generating projects. #82 (completed with PR #86 )
- [x] Refactor maven command history. (completed with PR #87 )
